import { address, type Address } from "@solana/kit";

import forgeIdl from "./generated/forge.json" with { type: "json" };

export type IdlType =
  | "bool"
  | "u8"
  | "u16"
  | "u32"
  | "u64"
  | "i64"
  | "pubkey"
  | { array: [IdlType, number] }
  | { defined: { name: string } };

export interface IdlField {
  name: string;
  type: IdlType;
}

export interface IdlInstructionAccount {
  name: string;
  writable?: boolean;
  signer?: boolean;
  address?: string;
}

export interface IdlInstruction {
  name: string;
  discriminator: number[];
  accounts: IdlInstructionAccount[];
  args: IdlField[];
}

export interface IdlTypeDef {
  name: string;
  type:
    | { kind: "struct"; fields: IdlField[] }
    | { kind: "enum"; variants: { name: string }[] };
}

export interface IdlError {
  code: number;
  name: string;
  msg: string;
}

export interface ForgeIdl {
  address: string;
  instructions: IdlInstruction[];
  accounts: { name: string; discriminator: number[] }[];
  types: IdlTypeDef[];
  errors: IdlError[];
}

/** The IDL generated by the Anchor build; the single source of truth for the codec. */
export const idl = forgeIdl as unknown as ForgeIdl;

export const FORGE_PROGRAM_ADDRESS: Address = address(idl.address);

export function idlInstruction(name: string): IdlInstruction {
  const found = idl.instructions.find((ix) => ix.name === name);
  if (!found) {
    throw new Error(`Instruction ${name} is not in the Forge IDL`);
  }
  return found;
}

export function idlTypeDef(name: string): IdlTypeDef {
  const found = idl.types.find((t) => t.name === name);
  if (!found) {
    throw new Error(`Type ${name} is not in the Forge IDL`);
  }
  return found;
}

export function idlAccountDiscriminator(name: string): number[] {
  const found = idl.accounts.find((a) => a.name === name);
  if (!found) {
    throw new Error(`Account ${name} is not in the Forge IDL`);
  }
  return found.discriminator;
}
